### ISSUE TITLE
Permanent Shadows when using Sodium

### ISSUE THREAD

**Issue by McDeans** [PhiPro95/mc-fixes#1]
Your lighting fix works great without it but I just thought I'd show what I experienced.
https://www.curseforge.com/minecraft/mc-mods/sodium
![2020-08-04_01 42 36](https://user-images.githubusercontent.com/69191753/89274627-0c1b2c80-d5f6-11ea-9d45-0cdfbbc815d4.png)
![2020-08-04_01 42 37](https://user-images.githubusercontent.com/69191753/89274634-0d4c5980-d5f6-11ea-89f3-5b47e6e0ffb9.png)
![2020-08-04_01 42 38](https://user-images.githubusercontent.com/69191753/89274639-0de4f000-d5f6-11ea-8f64-db8ddf0d21b5.png)
![2020-08-04_01 42 40](https://user-images.githubusercontent.com/69191753/89274640-0e7d8680-d5f6-11ea-9511-9afe224f30e2.png)

**Comment by PhiProven** [comment]
Thanks for your report. Working on a solution with JellySquid. Most likely this will be solved on Sodium's end.

**Comment by PhiProven** [comment]
I fixed this issue in the most recent version of my mod.
Just re-download it; I didn't bump the version number, so its still the `mc-fix_lighting-fixes-1.0.0` jar.

Let me know if any other issue pops up.
