### ISSUE TITLE
Not compatible with fabric-carpet mod

### ISSUE THREAD

**Issue by Fallen-Breath** [PhiPro95/mc-fixes#4]
fabric carpet >=1.4.8 seems not compatible with this mod, but fabric carpet 1.4.0 is compatible with

It crashes when entering the world

Crash reports
1.15.2: https://paste.ee/p/NnLSS
1.16.2: https://paste.ee/p/Sk8Gv

Although in the crash report it seems to be a carpet issue but the carpet code where it crashes is commited by you ([LevelPropagatorInterface](https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/mixins/LevelPropagatorInterface.java)) so I submit the issue here

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/32292d490904d4bccb274c41f9f591fb506d21b6
can close

**Comment by Fallen-Breath** [comment]
thanks

**Comment by Fallen-Breath** [comment]
Can you bring this compatibility change to 1.15.2 branch too? I'm not sure if updates can still apply to the 1.15.2 branch but it's about mod compatibility which might prevent people from using the last 1.15.2 carpet release
