### ISSUE TITLE
Loading screen freezes at 0% with Overworld Two

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [PhiPro95/mc-fixes#6]
When using this mod, [the 'new-perlin-noise' branch of Overworld Two](https://github.com/Gegy/overworld-two/tree/new-perlin-noise) (cannot be reproduced with the main 1.16.2 branch), and Fabric API (dependency of Overworld Two), then the loading screen freezes at 0% and there is a log spam. This also occurs when using [Phosphor-Fabric](https://github.com/CaffeineMC/phosphor-fabric) instead of this mod, if that narrows anything down. I also cannot reproduce with Starlight.

System/Minecraft:
- Minecraft 1.16.5
- Fabric Loader 0.11.3
- MultiMC 5 (0.6.12)
- Fabric API 0.32.5
- Windows 10
- AdoptOpenJDK 16 (OpenJ9)

Minecraft log: https://gist.github.com/DragonEggBedrockBreaking/f71d798a35121e0e83dbc2babe2484cc

**Comment by PhiProven** [comment]
See https://github.com/CaffeineMC/phosphor-fabric/issues/48#issuecomment-838853302.
